import type { Profile } from "@/types/profile";

 export const mockProfiles: Profile[] = [
  {
    id: '1',
    firstName: 'John',
    lastInitial: 'F',
    age: 27,
    sex: 'male',
    activities: [ 'Lifting',
                  'Running',
                  'Pickleball',
                  'Hiking',
                  'Basketball',
                  'Swimming',
                  'Golf',
                ],
    preferredTimes: ['Morning', 'Evening'],
    visibilityPreferences: ['anyone'],
    distanceMiles: 2.3,
    aboutMe:
      'I am looking for consistent activity partners who are reliable, easygoing, and interested in getting outside or training a few times a week. I usually prefer weekday evenings and weekends, and I am open to both casual sessions and more structured workouts depending on the activity. xxxxxxxxxxxxxxx',
    matchCount: 2,
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastInitial: 'M',
    age: 24,
    sex: 'female',
    activities: ['Pickleball', 'Hiking'],
    visibilityPreferences: ['female'],
    distanceMiles: 4.7,
    preferredTimes: ['Any'],
  },
  {
    id: '3',
    firstName: 'Alex',
    lastInitial: 'T',
    age: 31,
    sex: 'other',
    activities: ['Lifting', 'Basketball'],
    preferredTimes: ['Any'],
    distanceMiles: 8.2,
    visibilityPreferences: ['other'],
  },
  {
  id: '4',
    firstName: 'Josh',
    lastInitial: 'A',
    age: 31,
    sex: 'other',
    activities: ['Lifting', 'Basketball', 'Pickleball', 'Bowling', 'Running'],
    preferredTimes: ['Any'],
    distanceMiles: 8.2,
    visibilityPreferences: ['other'],
  },
  {
  id: '5',
    firstName: 'Maria',
    lastInitial: 'P',
    age: 28,
    sex: 'female',
    activities: ['Lifting', 'Basketball', 'Pickleball', 'Bowling', 'Running', 'Hiking'],
    preferredTimes: ['Any'],
    distanceMiles: 8.2,
    visibilityPreferences: ['female'],
  },
];
