import type { Posting } from '@/types/posting';
import { mockProfiles } from './mock-profiles';

export const mockPostings: Posting[] = [
  { id: 1, 
    title: 'test posting one', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-17T18:30:00'),
    distanceMiles: 2.3,
    creator: mockProfiles[0],
    participants: [
      mockProfiles[1],
      mockProfiles[3],
      mockProfiles[2],
      mockProfiles[4],
    ],
    locationName: 'Southview Park',
    maxParticipants: null,
    visibility: ['anyone'],
    ageRange: {
      min: 21,
      max: 35,
    },
   },
  { id: 2, 
    title: 'test posting two', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-19T18:30:00'),
    distanceMiles: 2.3,
    creator: mockProfiles[1],
    locationName: 'Grandwood Field',
    participants: [
        mockProfiles[0],
        mockProfiles[4],
      ],
    maxParticipants: 6,
    visibility: ['female'],
    ageRange: {
      min: 25,
      max: 30,
    },
   },
   { id: 3, 
    title: 'test posting three', 
    activity: 'Lifting', 
    dateTime: new Date('2026-07-19T18:30:00'),
    distanceMiles: 2.3,
    creator: mockProfiles[3],
    locationName: 'Oz Fitness',
    participants: [
      mockProfiles[1],
      mockProfiles[0],
      mockProfiles[2],
      mockProfiles[4],
    ],
    maxParticipants: 6,
    visibility: ['anyone'],
    ageRange: {
      min: 21,
      max: 50,
    },
   },
   { id: 4, 
    title: 'test posting four', 
    activity: 'Hiking', 
    dateTime: new Date('2026-07-22T18:30:00'),
    distanceMiles: 7.1,
    creator: mockProfiles[3],
    locationName: 'Great Canyon Park',
    participants: [
      mockProfiles[1],
      mockProfiles[0],
      mockProfiles[2],
    ],
    maxParticipants: 6,
    visibility: ['anyone'],
    ageRange: {
      min: 25,
      max: 30,
    },
   },
   { id: 5, 
    title: 'test posting five', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-17T18:30:00'),
    distanceMiles: 2.3,
    creator: mockProfiles[4],
    locationName: 'Rothwell Courts',
    participants: [
      mockProfiles[1],
      mockProfiles[2],
      mockProfiles[3],
      mockProfiles[0],
    ],
    maxParticipants: 5,
    visibility: ['anyone'],
    ageRange: {
      min: 21,
      max: 35,
    },
   },
  { id: 6, 
    title: 'test posting six', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-17T18:30:00'),
    distanceMiles: 2.3,
    creator: mockProfiles[3],
    locationName: 'Rothwell Courts',
    participants: [
      mockProfiles[1],
      mockProfiles[4],
      mockProfiles[2],
      mockProfiles[0],
    ],
    maxParticipants: 6,
    visibility: ['anyone'],
    ageRange: {
      min: 21,
      max: 35,
    }
   },
   { id: 7, 
    title: 'test posting seven', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-19T18:30:00'),
    distanceMiles: 2.3,
    creator: mockProfiles[1],
    locationName: 'Grandwood Field',
    participants: [
        mockProfiles[0],
        mockProfiles[3],
      ],
    maxParticipants: 6,
    visibility: ['female'],
    ageRange: {
      min: 25,
      max: 35,
    },
   },
];