import type { Posting } from '@/types/posting';

export const mockPostings: Posting[] = [
  { id: '1', 
    title: 'test posting one', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-17T18:30:00'),
    distanceMiles: 2.3,
    currentParticipants: 3,
    maxParticipants: null,
    visibility: ['anyone'],
    ageRange: {
      min: 21,
      max: 35,
    },
   },
  { id: '2', 
    title: 'test posting two', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-19T18:30:00'),
    distanceMiles: 2.3,
    currentParticipants: 2,
    maxParticipants: 6,
    visibility: ['female'],
    ageRange: {
      min: 25,
      max: 30,
    },
   },
   { id: '3', 
    title: 'test posting three', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-19T18:30:00'),
    distanceMiles: 2.3,
    currentParticipants: 2,
    maxParticipants: 6,
    visibility: ['anyone'],
    ageRange: {
      min: 21,
      max: 50,
    },
   },
   { id: '4', 
    title: 'test posting four', 
    activity: 'Lifting', 
    dateTime: new Date('2026-07-22T18:30:00'),
    distanceMiles: 7.1,
    currentParticipants: 5,
    maxParticipants: 6,
    visibility: ['anyone'],
    ageRange: {
      min: 25,
      max: 30,
    },
   },
   { id: '5', 
    title: 'test posting five', 
    activity: 'Basketball', 
    dateTime: new Date('2026-07-17T18:30:00'),
    distanceMiles: 2.3,
    currentParticipants: 3,
    maxParticipants: 3,
    visibility: ['anyone'],
    ageRange: {
      min: 21,
      max: 35,
    },
   },
];