import type { Profile } from '@/types/profile';

export const mockProfiles: Profile[] = [
  {
    id: 1,
    userId: 1,
    firstName: 'John',
    lastName: 'Finch',
    dateOfBirth: '1999-11-11',
    sex: 'male',
    activities: [
      'Lifting',
      'Running',
      'Pickleball',
      'Hiking',
      'Basketball',
      'Swimming',
      'Golf',
    ],
    preferredTimes: ['Morning', 'Evening'],
    visibilityPreferences: ['anyone'],
    aboutMe:
      'I am looking for consistent activity partners who are reliable, easygoing, and interested in getting outside or training a few times a week. I usually prefer weekday evenings and weekends, and I am open to both casual sessions and more structured workouts depending on the activity. xxxxxxxxxxxxxxx',
  },
  {
    id: 2,
    userId: 2,
    firstName: 'Sarah',
    lastName: 'Mcquire',
    dateOfBirth: '2002-06-01',
    sex: 'female',
    activities: ['Pickleball', 'Hiking'],
    visibilityPreferences: ['female'],
    preferredTimes: ['Any'],
  },
  {
    id: 3,
    userId: 3,
    firstName: 'Alex',
    lastName: 'Tulos',
    dateOfBirth: '1995-09-12',
    sex: 'other',
    activities: ['Lifting', 'Basketball'],
    preferredTimes: ['Any'],
    visibilityPreferences: ['other'],
  },
  {
    id: 4,
    userId: 4,
    firstName: 'Josh',
    lastName: 'Allen',
    dateOfBirth: '1995-07-05',
    sex: 'other',
    activities: ['Lifting', 'Basketball', 'Pickleball', 'Bowling', 'Running'],
    preferredTimes: ['Any'],
    visibilityPreferences: ['other'],
  },
  {
    id: 5,
    userId: 5,
    firstName: 'Maria',
    lastName: 'Panzeri',
    dateOfBirth: '1998-08-02',
    sex: 'female',
    activities: ['Lifting', 'Basketball', 'Pickleball', 'Bowling', 'Running', 'Hiking'],
    preferredTimes: ['Any'],
    visibilityPreferences: ['female'],
  },
];
